server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 120.48.19.4:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/acl/**
        - id: service-biz
          uri: lb://service-biz
          predicates:
            - Path=/biz/**