server:
  # 服务端口
  port: 8002

spring:
  application:
    # 服务名
    name: service-acl

  cloud:
    nacos:
      discovery:
        server-addr: 120.48.19.4:8848

  datasource:
    # 数据库连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.48.19.4:5432/postgres?currentSchema=lte&stringtype=unspecified&TimeZone=Asia/Shanghai&reWriteBatchedInserts=true
    username: root
    password: Q6^pw0*lb$@Ezv#&
    druid:
      filters: config, stat, log4j2
      initial-size: 1
      min-idle: 1
      max-active: 5
      validation-query: select 1;
      validation-query-timeout: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 180000
      phy-timeout-millis: 15000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      aop-patterns: "team.lte.*"
      # Druid Monitor
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        profile-enable: true
      stat-view-servlet:
        allow:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false

  jackson:
    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: team/lte/aclservice/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: "null"
      logic-not-delete-value: 0

logging:
  level:
    root: info