spring:
  application:
    # 服务名
    name: service-ucenter

  profiles:
    # 环境设置
    active: prod

  datasource:
    # 数据库连接
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: team/lte/ucenterservice/mapper/xml/*.xml