server:
  # 服务端口
  port: 8001

spring:
  # MySQL数据库连接
  # TODO: 更换连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lte?serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: team/lte/businessquery/mapper/xml/*.xml

logging:
  level:
    root: info