spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.4:8848

  # 数据库连接
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.4:5432/postgres?currentSchema=lte&stringtype=unspecified&TimeZone=Asia/Shanghai&reWriteBatchedInserts=true
    username: root
    password: Q6^pw0*lb$@Ezv#&

logging:
  level:
    root: info