server:
  # 服务端口
  port: 8001

spring:
  # 数据库连接
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.48.19.4:5432/postgres?currentSchema=lte&stringtype=unspecified&TimeZone=Asia/Shanghai&reWriteBatchedInserts=true
    username: root
    password: Q6^pw0*lb$@Ezv#&

logging:
  level:
    root: info